ALTER TABLE EMPLOYEES 
ADD CREATED_ON DATETIME NOT NULL DEFAULT DATETIME;

ALTER TABLE EMPLOYEES 
ADD MODIFIED_ON DATETIME NOT NULL DEFAULT DATETIME;

UPDATE EMPLOYEES SET CREATED_ON = DATETIME();
UPDATE EMPLOYEES SET MODIFIED_ON = DATETIME();